events_project/urls.py
from registration.backends.simple.views import RegistrationView
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include
from myevents import views

class ResetView(auth_views.LoginView):
    @property
    def success_url(self):
        return reverse('auth_login')

class ActivationCompleteView(auth_views.LoginView):
    @property
    def success_url(self):
        return reverse('auth_login')

urlpatterns = [ 
	path('', views.index, name='index'),
	path('myevents/', include('myevents.urls')),
    path('accounts/logout/<int:pk>/', RegistrationView.as_view(), name='registration_logout'),
    path('accounts/password/reset/complete/', ResetView.as_view(), name='reset_password'),
    path('accounts/activate/complete/', ActivationCompleteView.as_view(), name='activation_complete'),
    path('accounts/', include('registration.backends.default.urls')),
    path('admin/', admin.site.urls),
    path('accounts/profile/', views.profile, name='profile'),
]

myevents/urls.py
from django.urls import path
from myevents import views

app_name = 'myevents'

urlpatterns = [
	path('', views.index, name='index'),
	path('table_view/', views.table_view, name='table_view'),
    path('about/', views.about, name='about'),
    path('add_event/', views.add_event, name='add_event'),
    path('subset/', views.SubsetView.as_view(), name='subset'),
    path('event/<int:event_id>/', views.show_event, name='show_event'),
    path('event/<int:event_id>/edit', views.edit_event, name='edit_event'),
    path('delete/<int:event_id>/', views.delete, name='delete'),
]

myevents/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.template.defaultfilters import slugify 
from django.utils import timezone
from datetime import datetime, timedelta
from myevents.choices import *

class Event(models.Model):

	#basics
	title = models.CharField(max_length=128)
	description = models.TextField()
	join = models.URLField(max_length=200) 
	tags = TaggableManager()
	category = models.CharField(max_length=128, choices=CAT_CHOICES, default='other')

	#start, end, and duration
	start = models.DateTimeField()
	end = models.DateTimeField()

	#assign user origin
	user = models.ForeignKey('auth.User', on_delete=models.CASCADE)

	def __str__(self):
		return self.title

	def as_json(self):
		return dict(
            id=self.id, 
            title=self.title,
            day=self.day, 
            time=self.time,
            duration=self.duration,
            join=self.join,
            description=self.description,
            )

myevents/forms.py
from django import forms
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify 
from myevents.models import Event
from datetime import datetime, timedelta
from tempus_dominus.widgets import DatePicker, TimePicker, DateTimePicker
from taggit.forms import *
from myevents.choices import *
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from taggit.forms import TagWidget

class EventForm(forms.ModelForm):

	#basics
    title = forms.CharField(max_length=128, label="Event title")
    description = forms.CharField(widget=forms.Textarea())
    join = forms.URLField(max_length=200, required=False, label="Link to join event", initial="http://")
    category = forms.ChoiceField(choices=CAT_CHOICES)

    #datetimepicker
    start = forms.DateTimeField(
    	input_formats=['%m/%d/%Y %I:%M %p'],
        widget=DateTimePicker(
        	options={
        		'useCurrent': True,
        		'collapse': True,
        		'format': 'MM/DD/YYYY hh:mm A',
                'icons': {
                    'time': 'far fa-clock',
                    'date': 'fa fa-calendar',
                },
        	},
        	attrs={
        		'append': 'fa fa-calendar',
        		'icon_toggle': True,
        	}
        ),
        label="Start time (in EST)",
    )
    end = forms.DateTimeField(
    	input_formats=['%m/%d/%Y %I:%M %p'],
        widget=DateTimePicker(
        	options={
        		'useCurrent': True,
        		'collapse': True,
        		'format': 'MM/DD/YYYY hh:mm A',
                'icons': {
                    'time': 'far fa-clock',
                    'date': 'fa fa-calendar',
                },
        	},
        	attrs={
        		'append': 'fa fa-calendar',
        		'icon_toggle': True,
        	}
        ),
        label="End time (in EST)",
    )

    tags = TagField(
        widget=TagWidget(
            attrs={
                'data-role': 'tagsinput',
            },
        ),
        label="Keywords",
        required=False,
    )

    class Meta:
        model = Event
        exclude = ('user',)

    def clean(self):
        cleaned_data = super().clean()

        start = cleaned_data.get('start')
        end = cleaned_data.get('end')

        if start and end and end <= start:
            raise forms.ValidationError(
                "Oops. Your event's end must be after start."
            )
        
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields['description'].widget.attrs['rows'] = 4
        self.fields['description'].widget.attrs['columns'] = 15

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
    	model = User
    	fields = ('username', 'email', 'password',)

myevents/views.py
from django.shortcuts import render
from myevents.models import Event
from myevents.forms import EventForm, UserForm
from taggit.models import Tag
from django.shortcuts import redirect
from django.template.defaultfilters import slugify 
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.views.generic import View
from django.template.loader import render_to_string
from myevents.utils import *
from django.core import serializers
import logging
import json

logger = logging.getLogger(__name__)

def index(request):
	events = Event.objects.all().order_by('start')
	events_mod = querySetter(events)
	events_tod = getToday(events)
	events_tod
	context_dict = {
		'events': events_mod,
		'today': events_tod,
	}
	return render(request, 'myevents/index.html', context=context_dict)

def table_view(request):
	events = Event.objects.all().order_by('start')
	events_mod = querySetter(events)
	events_tod = getToday(events)
	events_tod
	context_dict = {
		'events': events_mod,
		'today': events_tod,
	}
	return render(request, 'myevents/table_view.html', context=context_dict)

def about(request):
	return render(request, 'myevents/about.html', context = {'boldmessage': 'This was put together by sachinpatel.'})

@login_required
def add_event(request):
	
	form = EventForm()

	if request.method == 'POST':
		form = EventForm(request.POST)

		if form.is_valid():

			event = form.save(commit=False)
			event.user = request.user
			event.save()
			form.save_m2m()

			return redirect(reverse('myevents:index'))

		else:
			print(form.errors)

	context_dict = {'form': form}

	return render(request, 'myevents/add_event.html', context=context_dict)

@login_required
def edit_event(request, event_id):

	myevent = Event.objects.get(id=event_id)

	form = EventForm(instance=myevent)

	if request.method == 'POST':
		form = EventForm(request.POST, instance=myevent)

		if form.is_valid():

			event = form.save(commit=False)
			event.user = request.user
			event.save()
			form.save_m2m()

			return redirect(reverse('myevents:index'))

		else:
			print(form.errors)

	context_dict = {'form': form}

	return render(request, 'myevents/edit_event.html', context=context_dict)

def show_event(request, event_id):

	myEvent = Event.objects.get(id=event_id)
	context_dict = {
		'event': myEvent, 
	}
	logger.error(myEvent)
	if myEvent:
		return render(request, 'myevents/event.html', context=context_dict)
	return HttpResponse("Hm, doesn't seem to be a valid event..")

class SubsetView(View):

	def get(self, request):
		category_id = request.GET['category_id']
		events = Event.objects.all().order_by('start')
		if category_id != 'all':
			events = Event.objects.filter(category=category_id).order_by('start')
			
		myevents = querySetter(events)

		serialized_events = [ob.as_json() for ob in myevents]
		return JsonResponse(serialized_events, safe=False)

@login_required
def profile(request):
	user = request.user
	context_dict = {
		'user': user,
		'events': Event.objects.filter(user=user),
	}
	return render(request, 'myevents/profile.html', context=context_dict)

@login_required
def delete(request, event_id):
	event = Event.objects.get(id=event_id)
	event.delete()
	return redirect(reverse('profile'))

templates/myevents/about.html
{% extends 'myevents/base.html' %}
{% load static %}

{% block head_block%}
	<title>About</title>
	<link rel="stylesheet" href="{% static 'my.css' %}">
{% endblock %}

{% block nav_block %}
{% endblock %}

{% block body_block %}

	<div class="py-5">
		<h2 class="text-primary">What we're about</h2>
		<p class="lead text-secondary">During this period of social distancing and isolation, it's hard to remain engaged with our communities. This is just one small tool that can help us feel and stay connected. And we're always eager for feedback!</p>
	</div>

	<div class="alert alert-primary" role="alert">
		<strong>Public Service Announcement</strong>
		<p>Unfortunately, the videoconferencing community has been experiencing a lot of video hijacking and cyber harassment. Privacy features are still being developed on various platforms, but please be mindful of this when you post a public link. Thanks!</p>
	</div>
{% endblock %}

templates/myevents/add_event.html
{% extends 'myevents/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_block%}
	<title>Add an event</title>
	<link rel="stylesheet" href="{% static 'my.css' %}">
{% endblock %}

{% block nav_block %}
{% endblock %}

{% block body_block %}

	<div class="col-md-6 offset-md-3">
		<div class="py-5 text-center">
	    	<h2 class="text-primary">Add an event</h2>
	    	<p class="lead text-secondary">Please add an event below. No worries if you don't know the specific link at the moment, and thanks for contributing.</p>
  		</div>

		{% if form.errors %}
			{% for field in form %}
				{% for error in field.errors %}
					<div class="alert alert-primary">
						<strong>{{ error|escape }}</strong>
					</div>
				{% endfor %}
			{% endfor %}
			{% for error in form.non_field_errors %}
				<div class="alert alert-primary">
					<strong>{{ error|escape }}</strong>
				</div>
			{% endfor %}
		{% endif %}

  		<div class="text-secondary">
			<form id="event_form" method="post" action="{% url 'myevents:add_event' %}">

				{% csrf_token %}

				{{ form.title|as_crispy_field }}

				<div class="form-row">
					<div class="col-md-6">
						{{ form.start|as_crispy_field }}
					</div>

					<div class="col-md-6">
						{{ form.end|as_crispy_field }}
					</div>
				</div>

				{{ form.join|as_crispy_field }}
				{{ form.category|as_crispy_field }}
				{{ form.description|as_crispy_field }}

				{{ form.tags|as_crispy_field }}

				<!--<hr class="mb-4">-->

				<button type="submit" class="btn btn-danger btn-block">Add event</button>
			</form>
		</div>
	</div>

{% endblock %}

{% block javascript %}

	<script src="{% static "js/my.js" %}" crossorigin="anonymous"></script>

{% endblock %}

templates/myevents/base.html
<!DOCTYPE html>
{% load static %}

<!--Load tag library-->
{% load bootstrap4 %}

<!--Load CSS-->
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!--Display messages as alerts-->
{% bootstrap_messages %}

<html>
    <head> 
    	<meta charset="utf-8">
  		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!--for custom b4-->
      <link rel="stylesheet" href="{% static 'custom_b4.css' %}">
      <link rel="stylesheet" href="{% static 'my.css' %}">

  		<!--for rendering icons-->
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/fontawesome.min.js" rel="stylesheet">
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/regular.min.js" rel="stylesheet">
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/solid.min.js" rel="stylesheet">
  		{{ form.media }}

      <!--for tag visualization with bootstrap4-->
      <script src="{% static 'admin/js/tagsinput.js' %}"></script>
      <link rel="stylesheet" href="{% static 'admin/css/tagsinput.css' %}">

  		{% block head_block%}
        <title>Video Conferencing Events</title>
      {% endblock %}
    </head>
    
    <body {% block bg_block %}class="bg-dark"{% endblock %}>
      <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">

              <li class="nav-item">
                <a class="nav-link" href="{% url 'myevents:index' %}">Home</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'myevents:about' %}">About</a>
              </li>

              {% if request.user.is_authenticated %}

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'myevents:add_event' %}">Add Event</a>
                </li>

                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">Profile</a>
                  <div class="dropdown-menu"ß>
                    <a class="dropdown-item" href="{% url 'profile' %}">My events</a>
                    <a class="dropdown-item disabled" href="#">Edit account</a>
                    <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'auth_logout' %}?next=/myevents/">Logout</a>
                  </div>
                </li>

              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
                </li>
              {% endif %}

              {% block nav_block %}
              {% endblock %}
            </ul>
          </div>
        </nav>
      </div>
            
    	<div class="container">
        	{% block body_block %}
        	{% endblock %}

          <footer class="my-5 pt-5 text-muted text-center text-small">
            <!--<p class="mb-1">Cheers!</p>-->
          </footer>

      </div>

      {% block javascript %}
      {% endblock javascript %}

    </body>



</html>

templates/myevents/edit_event.html
{% extends 'myevents/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_block%}
	<title>Edit event</title>
	<link rel="stylesheet" href="{% static 'my.css' %}">
{% endblock %}

{% block nav_block %}
{% endblock %}

{% block body_block %}

	<div class="col-md-6 offset-md-3">
		<div class="py-5 text-center">
	    	<h2 class="text-primary">Edit event</h2>
	    	<p class="lead text-secondary">Feel free to edit below.</p>
  		</div>

  		<div class="text-secondary">
			<form id="event_form" method="post">

				{% csrf_token %}

				{{ form.title|as_crispy_field }}

				<div class="form-row">
					<div class="col-md-6">
						{{ form.start|as_crispy_field }}
					</div>

					<div class="col-md-6">
						{{ form.end|as_crispy_field }}
					</div>
				</div>

				{{ form.join|as_crispy_field }}
				{{ form.category|as_crispy_field }}
				{{ form.description|as_crispy_field }}

				{{ form.tags|as_crispy_field }}

				<!--<hr class="mb-4">-->

				<button type="submit" class="btn btn-danger btn-block">Update event</button>
			</form>
		</div>
	</div>

{% endblock %}

templates/myevents/event.html
{% extends 'myevents/base.html' %}
{% load static %}
{% load event_extras %}

{% block head_block%}
	<title>Event Details</title>
{% endblock %}

{% block nav_block %}
{% endblock %}

{% block bg_block %}
	class="bg-light"
{% endblock %}

{% block body_block %}

	<div class="container pt-5 pb-3">
		<h2 class="text-primary">{{ event.title }}</h2>
	</div>

	<div class="row">

		<div class="col-md-8 order-md-1">
			<div class="container py-5">
				
				<p><strong>Description: </strong>{{ event.description }}</p>

				<p><strong>Link to join: </strong><a href="{{ event.join }}">{{ event.join }}</a></p>
			</div>
		</div>

		<div class="bg-light col-md-4 order-md-2 mb-4">
			<div class="container py-5">

				<div class="card box-shadow">
					
					<div class="card-header">
    					Quick deets
  					</div>

					<div class="card-body">
						<p>
							<i class="fa fa-calendar pr-2"></i>
							{{ event.start }} EST
						</p>
						<p>
							<i class="fa fa-hourglass-start pr-2"></i>
							{% delta event.start event.end %} long
						</p>
						<p>

							<i class="fa fa-filter pr-2"></i> 
							{{ event.category }}
						</p>
						<p>
							<i class="fa fa-user pr-2"></i>
							Added by {{ event.user }}
						</p>
					</div>

					<div class="card-footer">
						<div class="row">
							<div class="col text-center text-info">
								<a href=""><i class="fas fa-plus pr-2"></i>iCal</a>
							</div>
							<div class="col text-center text-info">
								<a href=""><i class="fas fa-plus pr-2"></i>gCal</a>
							</div>
					</div>
				</div>

			</div>
		</div>
	</div>

{% endblock %}

templates/myevents/index.html
{% extends 'myevents/base.html' %}
{% load static %}
{% load event_extras %}

{% block head_block%}
	<title>Events</title>
	<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
{% endblock %}

{% block nav_block %}
{% endblock %}

{% block body_block %}


	<div class="py-5">
		<h2 class="text-primary">Welcome</h2>
		<p class="lead text-secondary">With your help, we've put together a list of public, online events, facilitated by Zoom, BlueJeans, and other platforms. Take a look below to see if something piques your interest, and thanks for stopping by.</p>
	</div>

	<div class="py-3">
		<h5 class="text-primary">Upcoming events</h5>
	</div>

	<div class="custom-control custom-switch py-3">
		<input type="checkbox" class="custom-control-input" id="customSwitches">
		<label class="custom-control-label text-secondary" for="customSwitches">
			Table view
		</label>
	</div>

	<div>

		<button type="submit" class="btn btn-outline-danger active cardViewButtons mb-1" data-categoryid="all">All</button>

		{% get_all_categories as result %}
		{% for e in result %}
			<button type="submit" class="btn btn-outline-danger cardViewButtons mb-1" data-categoryid="{{ e.0 }}">{{ e.1 }}</button>
		{% endfor %}

	</div>

	<div class="row mt-4 pl-2 justify-content-left" id="cardView">
	{% for i in events %}
		<a href="/myevents/event/{{ i.id }}/" style="text-decoration: none;">
			<div class="card box-shadow mx-2 mb-3 indexCard" style="width:12rem; height:15rem;">

				<div class="card-body">
					<div style="height: 6rem; overflow: scroll; white-space: wrap;">
						<h5 class="card-title text-danger">{{ i.title }}</h5>
					</div>
					<h6 class="card-subtitle mt-2 mb-2 text-dark">{{ i.day}} @ {{i.time }} EST</h6>
					<p class="card-text text-truncate text-muted">{{ i.description }}</p>
				</div>
			</div>
		</a>
			
			<!--
			<div class="card-footer bg-white">
				<a href="/myevents/event/{{ i.id }}/" class="card-link text-muted">
					<i class="icon-chevron-right pr-2"></i>
					find out more
				</a>
			</div>
			-->

	{% endfor %}
	</div>

	<div id="emptyResult" class="text-secondary">
		{% if not events %}
			Sorry, there don't seem to be any events right now :/
		{% endif %}
	</div>

{% endblock %}

{% block javascript %}

	<script src="{% static "js/my.js" %}" crossorigin="anonymous"></script>

{% endblock %}

templates/myevents/profile.html
{% extends 'myevents/base.html' %}
{% load static %}
{% load event_extras %}

{% block head_block%}
	<title>My events</title>
	<link rel="stylesheet" href="{% static 'my.css' %}">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/fontawesome.min.js" rel="stylesheet">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/regular.min.js" rel="stylesheet">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/solid.min.js" rel="stylesheet">
{% endblock %}

{% block nav_block %}
{% endblock %}

{% block bg_block %}
	class="bg-light"
{% endblock %}

{% block body_block %}

	<div class="container pt-5 pb-3">
		<h2 class="text-primary">{{ user.username }}'s events</h2>
	</div>

	<div class="row">

		<div class="col-md-8 order-md-1">
			<div class="container py-3">
				{% for i in events %}

					<div class="card box-shadow mb-3" style="width:100%; height:13rem;">

						<div class="card-body">
							<h5 class="card-title text-danger">{{ i.title }}</h5>
							<p class="card-subtitle mb-2 text-dark"><strong>Start: </strong>{{ i.start}} EST</h6>
							<p class="card-subtitle mb-2 text-dark"><strong>End: </strong>{{ i.end}} EST</h6>		
							<p class="card-text text-truncate text-muted">{{ i.description }}</p>
						</div>

						<div class="card-footer bg-white">
							<div class="row">
								<div class="col text-center">
									<a href="/myevents/event/{{ i.id }}/" class="card-link text-muted"><i class="fa fa-chevron-right pr-2"></i>Event page
									</a>
								</div>
								<div class="col text-center">
									<a href="/myevents/event/{{ i.id }}/edit" class="card-link text-muted"><i class="fas fa-edit pr-2"></i>Edit
									</a>
								</div>
								<div class="col text-center">
									<a href="{% url 'myevents:delete' i.id %}" class="card-link text-muted confirm-delete"><i class="fas fa-trash pr-2"></i>Delete
									</a>
								</div>
							</div>
						</div>

					</div>

				{% endfor %}

			</div>
		</div>

		
	</div>

{% endblock %}

{% block javascript %}

	<script src="{% static "js/my.js" %}" crossorigin="anonymous"></script>

{% endblock %}

templates/myevents/table_view.html
{% extends 'myevents/base.html' %}
{% load static %}
{% load event_extras %}

{% block head_block%}
	<title>Events</title>
{% endblock %}

{% block nav_block %}
{% endblock %}

{% block bg_block %}
	class="bg-light"
{% endblock %}

{% block body_block %}


	<div class="py-5">
		<h2 class="text-primary">Welcome</h2>
		<p class="lead">With your help, we've put together a list of public, online events, facilitated by Zoom, BlueJeans, and other platforms. Take a look below to see if something piques your interest, and thanks for stopping by.</p>
	</div>

	<div class="py-3">
		<h5 class="text-primary">Upcoming events</h5>
	</div>

	<div class="custom-control custom-switch py-3">
		<input type="checkbox" class="custom-control-input" id="customSwitches" checked="true">
		<label class="custom-control-label" for="customSwitches">
			Table view
		</label>
	</div>

	<div>

		<button type="submit" class="btn btn-outline-success active tableViewButtons mb-1" data-categoryid="all">All</button>

		{% get_all_categories as result %}
		{% for e in result %}
			<button type="submit" class="btn btn-outline-success tableViewButtons mb-1" data-categoryid="{{ e.0 }}">{{ e.1 }}</button>
		{% endfor %}

	</div>

	<br>

	<!--
	<div class="input-group mb-4">
		<div class="input-group-prepend">
			<span class="input-group-text" id="basic-addon1">@</span>
		</div>
		<input type="text" class="form-control" placeholder="Search by keywords">
	</div>
	--> 
	
	<div>

		<table class="table" style="border-collapse:collapse;">
			<thead>
				<tr>
					<th scope="col">Event</th>
					<th scope="col">Date</th>
					<th scope="col">Start</th>
					<th scope="col">Duration</th>
				</tr>
			</thead>

			<tbody id="indexTable">

					{% for e in events %}

					<tr data-toggle="collapse" data-target="#id{{ e.id }}" class="colorChange">
						<td><a href='/myevents/event/{{ e.id }}/' class="text-success">{{ e.title }}</a></td>
						<td>{{ e.day }}</td>
						<td>{{ e.time }} EST</td>
						<td>{{ e.duration }}</td>
					</tr>
						
					<tr id="id{{ e.id }}" class="collapse hiddenRow">
			            <td colspan="6">
			            	<div class="card-body">
								<strong>Description:</strong>
								{{ e.description }}
								<br>
								<strong>Link to join meeting:</strong>
								<a href="{{ e.join }}">{{ e.join }}</a>
							</div>
			            </td>
				    </tr>

					{% endfor %}


			</tbody>

		</table>

		<div id="emptyResult">
			{% if not events %}
				Sorry, there don't seem to be any events right now :/
			{% endif %}
		</div>

	</div>

{% endblock %}

{% block javascript %}

	<script src="{% static "js/my.js" %}" crossorigin="anonymous"></script>

{% endblock %}